# Generated by Django 3.1.5 on 2021-01-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210120_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='strap',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
