# Generated by Django 3.1.5 on 2021-01-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_strap'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_warranty',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
