# Generated by Django 3.1.5 on 2021-02-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_has_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_warranty',
        ),
        migrations.AddField(
            model_name='product',
            name='year_warranty',
            field=models.CharField(choices=[('2', '2 years'), ('3', '3 years'), ('5', '5 years'), ('l', 'life')], default='2', max_length=1),
        ),
    ]
