# Generated by Django 3.1.5 on 2021-02-17 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210216_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_warranty',
        ),
    ]
